// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sdk/prover.proto

package sdkproto

import (
	commonproto "github.com/brevis-network/brevis-sdk/sdk/proto/commonproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_ERROR_UNDEFINED            ErrCode = 0
	ErrCode_ERROR_DEFAULT              ErrCode = 1
	ErrCode_ERROR_INVALID_INPUT        ErrCode = 2
	ErrCode_ERROR_INVALID_CUSTOM_INPUT ErrCode = 3
	ErrCode_ERROR_FAILED_TO_PROVE      ErrCode = 4
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0: "ERROR_UNDEFINED",
		1: "ERROR_DEFAULT",
		2: "ERROR_INVALID_INPUT",
		3: "ERROR_INVALID_CUSTOM_INPUT",
		4: "ERROR_FAILED_TO_PROVE",
	}
	ErrCode_value = map[string]int32{
		"ERROR_UNDEFINED":            0,
		"ERROR_DEFAULT":              1,
		"ERROR_INVALID_INPUT":        2,
		"ERROR_INVALID_CUSTOM_INPUT": 3,
		"ERROR_FAILED_TO_PROVE":      4,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_prover_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_sdk_prover_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_sdk_prover_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_sdk_prover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_prover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_sdk_prover_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *Err                   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_sdk_prover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_prover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_sdk_prover_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetErr() *Err {
	if x != nil {
		return x.Err
	}
	return nil
}

type ProveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipts      []*IndexedReceipt      `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	Storages      []*IndexedStorage      `protobuf:"bytes,2,rep,name=storages,proto3" json:"storages,omitempty"`
	Transactions  []*IndexedTransaction  `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	CustomInput   *CustomInput           `protobuf:"bytes,4,opt,name=custom_input,json=customInput,proto3" json:"custom_input,omitempty"`
	SrcChainId    uint64                 `protobuf:"varint,5,opt,name=src_chain_id,json=srcChainId,proto3" json:"src_chain_id,omitempty"`
	CircuitName   string                 `protobuf:"bytes,6,opt,name=circuit_name,json=circuitName,proto3" json:"circuit_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveRequest) Reset() {
	*x = ProveRequest{}
	mi := &file_sdk_prover_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveRequest) ProtoMessage() {}

func (x *ProveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_prover_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveRequest.ProtoReflect.Descriptor instead.
func (*ProveRequest) Descriptor() ([]byte, []int) {
	return file_sdk_prover_proto_rawDescGZIP(), []int{2}
}

func (x *ProveRequest) GetReceipts() []*IndexedReceipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

func (x *ProveRequest) GetStorages() []*IndexedStorage {
	if x != nil {
		return x.Storages
	}
	return nil
}

func (x *ProveRequest) GetTransactions() []*IndexedTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ProveRequest) GetCustomInput() *CustomInput {
	if x != nil {
		return x.CustomInput
	}
	return nil
}

func (x *ProveRequest) GetSrcChainId() uint64 {
	if x != nil {
		return x.SrcChainId
	}
	return 0
}

func (x *ProveRequest) GetCircuitName() string {
	if x != nil {
		return x.CircuitName
	}
	return ""
}

type ProveResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Err           *Err                        `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Proof         string                      `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	CircuitInfo   *commonproto.AppCircuitInfo `protobuf:"bytes,3,opt,name=circuit_info,json=circuitInfo,proto3" json:"circuit_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveResponse) Reset() {
	*x = ProveResponse{}
	mi := &file_sdk_prover_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveResponse) ProtoMessage() {}

func (x *ProveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_prover_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveResponse.ProtoReflect.Descriptor instead.
func (*ProveResponse) Descriptor() ([]byte, []int) {
	return file_sdk_prover_proto_rawDescGZIP(), []int{3}
}

func (x *ProveResponse) GetErr() *Err {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *ProveResponse) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

func (x *ProveResponse) GetCircuitInfo() *commonproto.AppCircuitInfo {
	if x != nil {
		return x.CircuitInfo
	}
	return nil
}

type ProveAsyncResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Err     *Err                   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	ProofId string                 `protobuf:"bytes,2,opt,name=proof_id,json=proofId,proto3" json:"proof_id,omitempty"`
	// circuit_info is the partial circuit info to submit to Brevis gateway
	// and trigger the data proof process
	CircuitInfo   *commonproto.AppCircuitInfo `protobuf:"bytes,3,opt,name=circuit_info,json=circuitInfo,proto3" json:"circuit_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveAsyncResponse) Reset() {
	*x = ProveAsyncResponse{}
	mi := &file_sdk_prover_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveAsyncResponse) ProtoMessage() {}

func (x *ProveAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_prover_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveAsyncResponse.ProtoReflect.Descriptor instead.
func (*ProveAsyncResponse) Descriptor() ([]byte, []int) {
	return file_sdk_prover_proto_rawDescGZIP(), []int{4}
}

func (x *ProveAsyncResponse) GetErr() *Err {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *ProveAsyncResponse) GetProofId() string {
	if x != nil {
		return x.ProofId
	}
	return ""
}

func (x *ProveAsyncResponse) GetCircuitInfo() *commonproto.AppCircuitInfo {
	if x != nil {
		return x.CircuitInfo
	}
	return nil
}

type GetProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProofId       string                 `protobuf:"bytes,1,opt,name=proof_id,json=proofId,proto3" json:"proof_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofRequest) Reset() {
	*x = GetProofRequest{}
	mi := &file_sdk_prover_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofRequest) ProtoMessage() {}

func (x *GetProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_prover_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofRequest.ProtoReflect.Descriptor instead.
func (*GetProofRequest) Descriptor() ([]byte, []int) {
	return file_sdk_prover_proto_rawDescGZIP(), []int{5}
}

func (x *GetProofRequest) GetProofId() string {
	if x != nil {
		return x.ProofId
	}
	return ""
}

type GetProofResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// err can be undefined or ERROR_FAILED_TO_PROVE
	Err *Err `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	// proof is an empty string until proving is finished
	Proof string `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// circuit_info to submit to Brevis gateway along with the app proof
	CircuitInfo   *commonproto.AppCircuitInfo `protobuf:"bytes,3,opt,name=circuit_info,json=circuitInfo,proto3" json:"circuit_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofResponse) Reset() {
	*x = GetProofResponse{}
	mi := &file_sdk_prover_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofResponse) ProtoMessage() {}

func (x *GetProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_prover_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofResponse.ProtoReflect.Descriptor instead.
func (*GetProofResponse) Descriptor() ([]byte, []int) {
	return file_sdk_prover_proto_rawDescGZIP(), []int{6}
}

func (x *GetProofResponse) GetErr() *Err {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *GetProofResponse) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

func (x *GetProofResponse) GetCircuitInfo() *commonproto.AppCircuitInfo {
	if x != nil {
		return x.CircuitInfo
	}
	return nil
}

type DeleteProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProofId       string                 `protobuf:"bytes,1,opt,name=proof_id,json=proofId,proto3" json:"proof_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProofRequest) Reset() {
	*x = DeleteProofRequest{}
	mi := &file_sdk_prover_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProofRequest) ProtoMessage() {}

func (x *DeleteProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_prover_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProofRequest.ProtoReflect.Descriptor instead.
func (*DeleteProofRequest) Descriptor() ([]byte, []int) {
	return file_sdk_prover_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProofRequest) GetProofId() string {
	if x != nil {
		return x.ProofId
	}
	return ""
}

type DeleteProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *Err                   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProofResponse) Reset() {
	*x = DeleteProofResponse{}
	mi := &file_sdk_prover_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProofResponse) ProtoMessage() {}

func (x *DeleteProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_prover_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProofResponse.ProtoReflect.Descriptor instead.
func (*DeleteProofResponse) Descriptor() ([]byte, []int) {
	return file_sdk_prover_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProofResponse) GetErr() *Err {
	if x != nil {
		return x.Err
	}
	return nil
}

type Err struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrCode                `protobuf:"varint,1,opt,name=code,proto3,enum=sdk.ErrCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Err) Reset() {
	*x = Err{}
	mi := &file_sdk_prover_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Err) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Err) ProtoMessage() {}

func (x *Err) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_prover_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Err.ProtoReflect.Descriptor instead.
func (*Err) Descriptor() ([]byte, []int) {
	return file_sdk_prover_proto_rawDescGZIP(), []int{9}
}

func (x *Err) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_ERROR_UNDEFINED
}

func (x *Err) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_sdk_prover_proto protoreflect.FileDescriptor

const file_sdk_prover_proto_rawDesc = "" +
	"\n" +
	"\x10sdk/prover.proto\x12\x03sdk\x1a\x0fsdk/types.proto\x1a\x19common/circuit_data.proto\x1a\x1cgoogle/api/annotations.proto\"\x0f\n" +
	"\rHealthRequest\",\n" +
	"\x0eHealthResponse\x12\x1a\n" +
	"\x03err\x18\x01 \x01(\v2\b.sdk.ErrR\x03err\"\xa7\x02\n" +
	"\fProveRequest\x12/\n" +
	"\breceipts\x18\x01 \x03(\v2\x13.sdk.IndexedReceiptR\breceipts\x12/\n" +
	"\bstorages\x18\x02 \x03(\v2\x13.sdk.IndexedStorageR\bstorages\x12;\n" +
	"\ftransactions\x18\x03 \x03(\v2\x17.sdk.IndexedTransactionR\ftransactions\x123\n" +
	"\fcustom_input\x18\x04 \x01(\v2\x10.sdk.CustomInputR\vcustomInput\x12 \n" +
	"\fsrc_chain_id\x18\x05 \x01(\x04R\n" +
	"srcChainId\x12!\n" +
	"\fcircuit_name\x18\x06 \x01(\tR\vcircuitName\"|\n" +
	"\rProveResponse\x12\x1a\n" +
	"\x03err\x18\x01 \x01(\v2\b.sdk.ErrR\x03err\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\tR\x05proof\x129\n" +
	"\fcircuit_info\x18\x03 \x01(\v2\x16.common.AppCircuitInfoR\vcircuitInfo\"\x86\x01\n" +
	"\x12ProveAsyncResponse\x12\x1a\n" +
	"\x03err\x18\x01 \x01(\v2\b.sdk.ErrR\x03err\x12\x19\n" +
	"\bproof_id\x18\x02 \x01(\tR\aproofId\x129\n" +
	"\fcircuit_info\x18\x03 \x01(\v2\x16.common.AppCircuitInfoR\vcircuitInfo\",\n" +
	"\x0fGetProofRequest\x12\x19\n" +
	"\bproof_id\x18\x01 \x01(\tR\aproofId\"\x7f\n" +
	"\x10GetProofResponse\x12\x1a\n" +
	"\x03err\x18\x01 \x01(\v2\b.sdk.ErrR\x03err\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\tR\x05proof\x129\n" +
	"\fcircuit_info\x18\x03 \x01(\v2\x16.common.AppCircuitInfoR\vcircuitInfo\"/\n" +
	"\x12DeleteProofRequest\x12\x19\n" +
	"\bproof_id\x18\x01 \x01(\tR\aproofId\"1\n" +
	"\x13DeleteProofResponse\x12\x1a\n" +
	"\x03err\x18\x01 \x01(\v2\b.sdk.ErrR\x03err\"9\n" +
	"\x03Err\x12 \n" +
	"\x04code\x18\x01 \x01(\x0e2\f.sdk.ErrCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg*\x85\x01\n" +
	"\aErrCode\x12\x13\n" +
	"\x0fERROR_UNDEFINED\x10\x00\x12\x11\n" +
	"\rERROR_DEFAULT\x10\x01\x12\x17\n" +
	"\x13ERROR_INVALID_INPUT\x10\x02\x12\x1e\n" +
	"\x1aERROR_INVALID_CUSTOM_INPUT\x10\x03\x12\x19\n" +
	"\x15ERROR_FAILED_TO_PROVE\x10\x042\x8c\x03\n" +
	"\x06Prover\x12E\n" +
	"\x05Prove\x12\x11.sdk.ProveRequest\x1a\x12.sdk.ProveResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/sdk/prove\x12U\n" +
	"\n" +
	"ProveAsync\x12\x11.sdk.ProveRequest\x1a\x17.sdk.ProveAsyncResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/sdk/prove-async\x12O\n" +
	"\bGetProof\x12\x14.sdk.GetProofRequest\x1a\x15.sdk.GetProofResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/sdk/get-proof\x12^\n" +
	"\vDeleteProof\x12\x17.sdk.DeleteProofRequest\x1a\x18.sdk.DeleteProofResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/sdk/delete-proof\x123\n" +
	"\x06Health\x12\x12.sdk.HealthRequest\x1a\x13.sdk.HealthResponse\"\x00b\x06proto3"

var (
	file_sdk_prover_proto_rawDescOnce sync.Once
	file_sdk_prover_proto_rawDescData []byte
)

func file_sdk_prover_proto_rawDescGZIP() []byte {
	file_sdk_prover_proto_rawDescOnce.Do(func() {
		file_sdk_prover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_prover_proto_rawDesc), len(file_sdk_prover_proto_rawDesc)))
	})
	return file_sdk_prover_proto_rawDescData
}

var file_sdk_prover_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_prover_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sdk_prover_proto_goTypes = []any{
	(ErrCode)(0),                       // 0: sdk.ErrCode
	(*HealthRequest)(nil),              // 1: sdk.HealthRequest
	(*HealthResponse)(nil),             // 2: sdk.HealthResponse
	(*ProveRequest)(nil),               // 3: sdk.ProveRequest
	(*ProveResponse)(nil),              // 4: sdk.ProveResponse
	(*ProveAsyncResponse)(nil),         // 5: sdk.ProveAsyncResponse
	(*GetProofRequest)(nil),            // 6: sdk.GetProofRequest
	(*GetProofResponse)(nil),           // 7: sdk.GetProofResponse
	(*DeleteProofRequest)(nil),         // 8: sdk.DeleteProofRequest
	(*DeleteProofResponse)(nil),        // 9: sdk.DeleteProofResponse
	(*Err)(nil),                        // 10: sdk.Err
	(*IndexedReceipt)(nil),             // 11: sdk.IndexedReceipt
	(*IndexedStorage)(nil),             // 12: sdk.IndexedStorage
	(*IndexedTransaction)(nil),         // 13: sdk.IndexedTransaction
	(*CustomInput)(nil),                // 14: sdk.CustomInput
	(*commonproto.AppCircuitInfo)(nil), // 15: common.AppCircuitInfo
}
var file_sdk_prover_proto_depIdxs = []int32{
	10, // 0: sdk.HealthResponse.err:type_name -> sdk.Err
	11, // 1: sdk.ProveRequest.receipts:type_name -> sdk.IndexedReceipt
	12, // 2: sdk.ProveRequest.storages:type_name -> sdk.IndexedStorage
	13, // 3: sdk.ProveRequest.transactions:type_name -> sdk.IndexedTransaction
	14, // 4: sdk.ProveRequest.custom_input:type_name -> sdk.CustomInput
	10, // 5: sdk.ProveResponse.err:type_name -> sdk.Err
	15, // 6: sdk.ProveResponse.circuit_info:type_name -> common.AppCircuitInfo
	10, // 7: sdk.ProveAsyncResponse.err:type_name -> sdk.Err
	15, // 8: sdk.ProveAsyncResponse.circuit_info:type_name -> common.AppCircuitInfo
	10, // 9: sdk.GetProofResponse.err:type_name -> sdk.Err
	15, // 10: sdk.GetProofResponse.circuit_info:type_name -> common.AppCircuitInfo
	10, // 11: sdk.DeleteProofResponse.err:type_name -> sdk.Err
	0,  // 12: sdk.Err.code:type_name -> sdk.ErrCode
	3,  // 13: sdk.Prover.Prove:input_type -> sdk.ProveRequest
	3,  // 14: sdk.Prover.ProveAsync:input_type -> sdk.ProveRequest
	6,  // 15: sdk.Prover.GetProof:input_type -> sdk.GetProofRequest
	8,  // 16: sdk.Prover.DeleteProof:input_type -> sdk.DeleteProofRequest
	1,  // 17: sdk.Prover.Health:input_type -> sdk.HealthRequest
	4,  // 18: sdk.Prover.Prove:output_type -> sdk.ProveResponse
	5,  // 19: sdk.Prover.ProveAsync:output_type -> sdk.ProveAsyncResponse
	7,  // 20: sdk.Prover.GetProof:output_type -> sdk.GetProofResponse
	9,  // 21: sdk.Prover.DeleteProof:output_type -> sdk.DeleteProofResponse
	2,  // 22: sdk.Prover.Health:output_type -> sdk.HealthResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_sdk_prover_proto_init() }
func file_sdk_prover_proto_init() {
	if File_sdk_prover_proto != nil {
		return
	}
	file_sdk_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_prover_proto_rawDesc), len(file_sdk_prover_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_prover_proto_goTypes,
		DependencyIndexes: file_sdk_prover_proto_depIdxs,
		EnumInfos:         file_sdk_prover_proto_enumTypes,
		MessageInfos:      file_sdk_prover_proto_msgTypes,
	}.Build()
	File_sdk_prover_proto = out.File
	file_sdk_prover_proto_goTypes = nil
	file_sdk_prover_proto_depIdxs = nil
}
