// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: brevis/gateway.proto

package gwproto

import (
	commonproto "github.com/brevis-network/brevis-sdk/sdk/proto/commonproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_ERROR_CODE_UNDEFINED                           ErrCode = 0
	ErrCode_ERROR_CODE_SLOT_VALUE_PROOF_GENERATION_FAILED  ErrCode = 1
	ErrCode_ERROR_CODE_TRANSACTION_PROOF_GENERATION_FAILED ErrCode = 2
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0: "ERROR_CODE_UNDEFINED",
		1: "ERROR_CODE_SLOT_VALUE_PROOF_GENERATION_FAILED",
		2: "ERROR_CODE_TRANSACTION_PROOF_GENERATION_FAILED",
	}
	ErrCode_value = map[string]int32{
		"ERROR_CODE_UNDEFINED":                           0,
		"ERROR_CODE_SLOT_VALUE_PROOF_GENERATION_FAILED":  1,
		"ERROR_CODE_TRANSACTION_PROOF_GENERATION_FAILED": 2,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_brevis_gateway_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_brevis_gateway_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{0}
}

type CheckStatus int32

const (
	CheckStatus_IN_PROGRESS CheckStatus = 0
	CheckStatus_COMPLETE    CheckStatus = 1
)

// Enum value maps for CheckStatus.
var (
	CheckStatus_name = map[int32]string{
		0: "IN_PROGRESS",
		1: "COMPLETE",
	}
	CheckStatus_value = map[string]int32{
		"IN_PROGRESS": 0,
		"COMPLETE":    1,
	}
)

func (x CheckStatus) Enum() *CheckStatus {
	p := new(CheckStatus)
	*p = x
	return p
}

func (x CheckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_brevis_gateway_proto_enumTypes[1].Descriptor()
}

func (CheckStatus) Type() protoreflect.EnumType {
	return &file_brevis_gateway_proto_enumTypes[1]
}

func (x CheckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckStatus.Descriptor instead.
func (CheckStatus) EnumDescriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{1}
}

type QueryOption int32

const (
	QueryOption_ZK_MODE QueryOption = 0
	QueryOption_OP_MODE QueryOption = 1
)

// Enum value maps for QueryOption.
var (
	QueryOption_name = map[int32]string{
		0: "ZK_MODE",
		1: "OP_MODE",
	}
	QueryOption_value = map[string]int32{
		"ZK_MODE": 0,
		"OP_MODE": 1,
	}
)

func (x QueryOption) Enum() *QueryOption {
	p := new(QueryOption)
	*p = x
	return p
}

func (x QueryOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryOption) Descriptor() protoreflect.EnumDescriptor {
	return file_brevis_gateway_proto_enumTypes[2].Descriptor()
}

func (QueryOption) Type() protoreflect.EnumType {
	return &file_brevis_gateway_proto_enumTypes[2]
}

func (x QueryOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryOption.Descriptor instead.
func (QueryOption) EnumDescriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{2}
}

type QueryStatus int32

const (
	QueryStatus_QS_UNKNOWN                      QueryStatus = 0
	QueryStatus_QS_TO_BE_PAID                   QueryStatus = 1
	QueryStatus_QS_PAID                         QueryStatus = 2
	QueryStatus_QS_PROOF_READY                  QueryStatus = 3
	QueryStatus_QS_COMPLETE                     QueryStatus = 4
	QueryStatus_QS_FAILED                       QueryStatus = 5
	QueryStatus_QS_OP_MESSAGE_PENDING           QueryStatus = 6
	QueryStatus_QS_OP_MESSAGE_READY             QueryStatus = 7
	QueryStatus_QS_OP_SUBMITTED                 QueryStatus = 8
	QueryStatus_QS_OP_MESSAGE_SUBMISSION_FAILED QueryStatus = 9
	QueryStatus_QS_OP_DISPUTING                 QueryStatus = 10
	QueryStatus_QS_OP_ASK_FOR_QUERY_DATA        QueryStatus = 11
	QueryStatus_QS_OP_QUERY_DATA_SUBMITTED      QueryStatus = 12
	QueryStatus_QS_OP_QUERY_DATA_POST_FAILED    QueryStatus = 13
	QueryStatus_QS_OP_ASK_FOR_QUERY_PROOF       QueryStatus = 14
	QueryStatus_QS_OP_DISPUTED                  QueryStatus = 15
	QueryStatus_QS_OP_ATTESTED                  QueryStatus = 16
	QueryStatus_QS_REFUNDED                     QueryStatus = 17
)

// Enum value maps for QueryStatus.
var (
	QueryStatus_name = map[int32]string{
		0:  "QS_UNKNOWN",
		1:  "QS_TO_BE_PAID",
		2:  "QS_PAID",
		3:  "QS_PROOF_READY",
		4:  "QS_COMPLETE",
		5:  "QS_FAILED",
		6:  "QS_OP_MESSAGE_PENDING",
		7:  "QS_OP_MESSAGE_READY",
		8:  "QS_OP_SUBMITTED",
		9:  "QS_OP_MESSAGE_SUBMISSION_FAILED",
		10: "QS_OP_DISPUTING",
		11: "QS_OP_ASK_FOR_QUERY_DATA",
		12: "QS_OP_QUERY_DATA_SUBMITTED",
		13: "QS_OP_QUERY_DATA_POST_FAILED",
		14: "QS_OP_ASK_FOR_QUERY_PROOF",
		15: "QS_OP_DISPUTED",
		16: "QS_OP_ATTESTED",
		17: "QS_REFUNDED",
	}
	QueryStatus_value = map[string]int32{
		"QS_UNKNOWN":                      0,
		"QS_TO_BE_PAID":                   1,
		"QS_PAID":                         2,
		"QS_PROOF_READY":                  3,
		"QS_COMPLETE":                     4,
		"QS_FAILED":                       5,
		"QS_OP_MESSAGE_PENDING":           6,
		"QS_OP_MESSAGE_READY":             7,
		"QS_OP_SUBMITTED":                 8,
		"QS_OP_MESSAGE_SUBMISSION_FAILED": 9,
		"QS_OP_DISPUTING":                 10,
		"QS_OP_ASK_FOR_QUERY_DATA":        11,
		"QS_OP_QUERY_DATA_SUBMITTED":      12,
		"QS_OP_QUERY_DATA_POST_FAILED":    13,
		"QS_OP_ASK_FOR_QUERY_PROOF":       14,
		"QS_OP_DISPUTED":                  15,
		"QS_OP_ATTESTED":                  16,
		"QS_REFUNDED":                     17,
	}
)

func (x QueryStatus) Enum() *QueryStatus {
	p := new(QueryStatus)
	*p = x
	return p
}

func (x QueryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_brevis_gateway_proto_enumTypes[3].Descriptor()
}

func (QueryStatus) Type() protoreflect.EnumType {
	return &file_brevis_gateway_proto_enumTypes[3]
}

func (x QueryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryStatus.Descriptor instead.
func (QueryStatus) EnumDescriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{3}
}

type ErrMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrCode                `protobuf:"varint,1,opt,name=code,proto3,enum=brevis.ErrCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrMsg) Reset() {
	*x = ErrMsg{}
	mi := &file_brevis_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrMsg) ProtoMessage() {}

func (x *ErrMsg) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrMsg.ProtoReflect.Descriptor instead.
func (*ErrMsg) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ErrMsg) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_ERROR_CODE_UNDEFINED
}

func (x *ErrMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PrepareQueryRequest struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	ChainId           uint64                      `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ReceiptInfos      []*ReceiptInfo              `protobuf:"bytes,2,rep,name=receipt_infos,json=receiptInfos,proto3" json:"receipt_infos,omitempty"`
	StorageQueryInfos []*StorageQueryInfo         `protobuf:"bytes,3,rep,name=storage_query_infos,json=storageQueryInfos,proto3" json:"storage_query_infos,omitempty"`
	TransactionInfos  []*TransactionInfo          `protobuf:"bytes,4,rep,name=transaction_infos,json=transactionInfos,proto3" json:"transaction_infos,omitempty"`
	AppCircuitInfo    *commonproto.AppCircuitInfo `protobuf:"bytes,5,opt,name=app_circuit_info,json=appCircuitInfo,proto3" json:"app_circuit_info,omitempty"`
	TargetChainId     uint64                      `protobuf:"varint,6,opt,name=target_chain_id,json=targetChainId,proto3" json:"target_chain_id,omitempty"`
	Option            QueryOption                 `protobuf:"varint,7,opt,name=option,proto3,enum=brevis.QueryOption" json:"option,omitempty"`
	// Deprecated: Marked as deprecated in brevis/gateway.proto.
	UsePlonky2       bool                          `protobuf:"varint,8,opt,name=use_plonky2,json=usePlonky2,proto3" json:"use_plonky2,omitempty"`
	UseVm            bool                          `protobuf:"varint,9,opt,name=use_vm,json=useVm,proto3" json:"use_vm,omitempty"`
	VmAppCircuitInfo *commonproto.VmAppCircuitInfo `protobuf:"bytes,10,opt,name=vm_app_circuit_info,json=vmAppCircuitInfo,proto3" json:"vm_app_circuit_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrepareQueryRequest) Reset() {
	*x = PrepareQueryRequest{}
	mi := &file_brevis_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareQueryRequest) ProtoMessage() {}

func (x *PrepareQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareQueryRequest.ProtoReflect.Descriptor instead.
func (*PrepareQueryRequest) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareQueryRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *PrepareQueryRequest) GetReceiptInfos() []*ReceiptInfo {
	if x != nil {
		return x.ReceiptInfos
	}
	return nil
}

func (x *PrepareQueryRequest) GetStorageQueryInfos() []*StorageQueryInfo {
	if x != nil {
		return x.StorageQueryInfos
	}
	return nil
}

func (x *PrepareQueryRequest) GetTransactionInfos() []*TransactionInfo {
	if x != nil {
		return x.TransactionInfos
	}
	return nil
}

func (x *PrepareQueryRequest) GetAppCircuitInfo() *commonproto.AppCircuitInfo {
	if x != nil {
		return x.AppCircuitInfo
	}
	return nil
}

func (x *PrepareQueryRequest) GetTargetChainId() uint64 {
	if x != nil {
		return x.TargetChainId
	}
	return 0
}

func (x *PrepareQueryRequest) GetOption() QueryOption {
	if x != nil {
		return x.Option
	}
	return QueryOption_ZK_MODE
}

// Deprecated: Marked as deprecated in brevis/gateway.proto.
func (x *PrepareQueryRequest) GetUsePlonky2() bool {
	if x != nil {
		return x.UsePlonky2
	}
	return false
}

func (x *PrepareQueryRequest) GetUseVm() bool {
	if x != nil {
		return x.UseVm
	}
	return false
}

func (x *PrepareQueryRequest) GetVmAppCircuitInfo() *commonproto.VmAppCircuitInfo {
	if x != nil {
		return x.VmAppCircuitInfo
	}
	return nil
}

type PrepareQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *ErrMsg                `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	QueryKey      *QueryKey              `protobuf:"bytes,2,opt,name=query_key,json=queryKey,proto3" json:"query_key,omitempty"`
	Fee           string                 `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareQueryResponse) Reset() {
	*x = PrepareQueryResponse{}
	mi := &file_brevis_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareQueryResponse) ProtoMessage() {}

func (x *PrepareQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareQueryResponse.ProtoReflect.Descriptor instead.
func (*PrepareQueryResponse) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareQueryResponse) GetErr() *ErrMsg {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *PrepareQueryResponse) GetQueryKey() *QueryKey {
	if x != nil {
		return x.QueryKey
	}
	return nil
}

func (x *PrepareQueryResponse) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

type SubmitAppCircuitProofRequest struct {
	state            protoimpl.MessageState               `protogen:"open.v1"`
	QueryKey         *QueryKey                            `protobuf:"bytes,1,opt,name=query_key,json=queryKey,proto3" json:"query_key,omitempty"`
	TargetChainId    uint64                               `protobuf:"varint,2,opt,name=target_chain_id,json=targetChainId,proto3" json:"target_chain_id,omitempty"`
	Proof            string                               `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	AppCircuitInfo   *commonproto.AppCircuitInfoWithProof `protobuf:"bytes,4,opt,name=app_circuit_info,json=appCircuitInfo,proto3" json:"app_circuit_info,omitempty"`
	VmAppCircuitInfo *commonproto.VmAppCircuitInfo        `protobuf:"bytes,5,opt,name=vm_app_circuit_info,json=vmAppCircuitInfo,proto3" json:"vm_app_circuit_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitAppCircuitProofRequest) Reset() {
	*x = SubmitAppCircuitProofRequest{}
	mi := &file_brevis_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAppCircuitProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAppCircuitProofRequest) ProtoMessage() {}

func (x *SubmitAppCircuitProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAppCircuitProofRequest.ProtoReflect.Descriptor instead.
func (*SubmitAppCircuitProofRequest) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitAppCircuitProofRequest) GetQueryKey() *QueryKey {
	if x != nil {
		return x.QueryKey
	}
	return nil
}

func (x *SubmitAppCircuitProofRequest) GetTargetChainId() uint64 {
	if x != nil {
		return x.TargetChainId
	}
	return 0
}

func (x *SubmitAppCircuitProofRequest) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

func (x *SubmitAppCircuitProofRequest) GetAppCircuitInfo() *commonproto.AppCircuitInfoWithProof {
	if x != nil {
		return x.AppCircuitInfo
	}
	return nil
}

func (x *SubmitAppCircuitProofRequest) GetVmAppCircuitInfo() *commonproto.VmAppCircuitInfo {
	if x != nil {
		return x.VmAppCircuitInfo
	}
	return nil
}

type SubmitAppCircuitProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *ErrMsg                `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAppCircuitProofResponse) Reset() {
	*x = SubmitAppCircuitProofResponse{}
	mi := &file_brevis_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAppCircuitProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAppCircuitProofResponse) ProtoMessage() {}

func (x *SubmitAppCircuitProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAppCircuitProofResponse.ProtoReflect.Descriptor instead.
func (*SubmitAppCircuitProofResponse) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitAppCircuitProofResponse) GetErr() *ErrMsg {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *SubmitAppCircuitProofResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetQueryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryKey      *QueryKey              `protobuf:"bytes,1,opt,name=query_key,json=queryKey,proto3" json:"query_key,omitempty"`
	TargetChainId uint64                 `protobuf:"varint,2,opt,name=target_chain_id,json=targetChainId,proto3" json:"target_chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryStatusRequest) Reset() {
	*x = GetQueryStatusRequest{}
	mi := &file_brevis_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryStatusRequest) ProtoMessage() {}

func (x *GetQueryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetQueryStatusRequest) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GetQueryStatusRequest) GetQueryKey() *QueryKey {
	if x != nil {
		return x.QueryKey
	}
	return nil
}

func (x *GetQueryStatusRequest) GetTargetChainId() uint64 {
	if x != nil {
		return x.TargetChainId
	}
	return 0
}

type GetQueryStatusResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Err                   *ErrMsg                `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Status                QueryStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=brevis.QueryStatus" json:"status,omitempty"`
	TxHash                string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Proof                 string                 `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	ProofData             *ProofData             `protobuf:"bytes,5,opt,name=proof_data,json=proofData,proto3" json:"proof_data,omitempty"`
	CircuitOutput         string                 `protobuf:"bytes,6,opt,name=circuit_output,json=circuitOutput,proto3" json:"circuit_output,omitempty"`
	ProofWithPublicInputs string                 `protobuf:"bytes,7,opt,name=proof_with_public_inputs,json=proofWithPublicInputs,proto3" json:"proof_with_public_inputs,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetQueryStatusResponse) Reset() {
	*x = GetQueryStatusResponse{}
	mi := &file_brevis_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryStatusResponse) ProtoMessage() {}

func (x *GetQueryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryStatusResponse.ProtoReflect.Descriptor instead.
func (*GetQueryStatusResponse) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GetQueryStatusResponse) GetErr() *ErrMsg {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *GetQueryStatusResponse) GetStatus() QueryStatus {
	if x != nil {
		return x.Status
	}
	return QueryStatus_QS_UNKNOWN
}

func (x *GetQueryStatusResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *GetQueryStatusResponse) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

func (x *GetQueryStatusResponse) GetProofData() *ProofData {
	if x != nil {
		return x.ProofData
	}
	return nil
}

func (x *GetQueryStatusResponse) GetCircuitOutput() string {
	if x != nil {
		return x.CircuitOutput
	}
	return ""
}

func (x *GetQueryStatusResponse) GetProofWithPublicInputs() string {
	if x != nil {
		return x.ProofWithPublicInputs
	}
	return ""
}

type GetQueryInfoForOPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryHash     string                 `protobuf:"bytes,1,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	TargetChainId uint64                 `protobuf:"varint,2,opt,name=target_chain_id,json=targetChainId,proto3" json:"target_chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryInfoForOPRequest) Reset() {
	*x = GetQueryInfoForOPRequest{}
	mi := &file_brevis_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryInfoForOPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryInfoForOPRequest) ProtoMessage() {}

func (x *GetQueryInfoForOPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryInfoForOPRequest.ProtoReflect.Descriptor instead.
func (*GetQueryInfoForOPRequest) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *GetQueryInfoForOPRequest) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

func (x *GetQueryInfoForOPRequest) GetTargetChainId() uint64 {
	if x != nil {
		return x.TargetChainId
	}
	return 0
}

type GetQueryInfoForOPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *ErrMsg                `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	QueryInfo     []byte                 `protobuf:"bytes,2,opt,name=query_info,json=queryInfo,proto3" json:"query_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryInfoForOPResponse) Reset() {
	*x = GetQueryInfoForOPResponse{}
	mi := &file_brevis_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryInfoForOPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryInfoForOPResponse) ProtoMessage() {}

func (x *GetQueryInfoForOPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryInfoForOPResponse.ProtoReflect.Descriptor instead.
func (*GetQueryInfoForOPResponse) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *GetQueryInfoForOPResponse) GetErr() *ErrMsg {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *GetQueryInfoForOPResponse) GetQueryInfo() []byte {
	if x != nil {
		return x.QueryInfo
	}
	return nil
}

type GetSingleRunParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryKey      *QueryKey              `protobuf:"bytes,1,opt,name=query_key,json=queryKey,proto3" json:"query_key,omitempty"`
	TargetChainId uint64                 `protobuf:"varint,2,opt,name=target_chain_id,json=targetChainId,proto3" json:"target_chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSingleRunParamsRequest) Reset() {
	*x = GetSingleRunParamsRequest{}
	mi := &file_brevis_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSingleRunParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleRunParamsRequest) ProtoMessage() {}

func (x *GetSingleRunParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleRunParamsRequest.ProtoReflect.Descriptor instead.
func (*GetSingleRunParamsRequest) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *GetSingleRunParamsRequest) GetQueryKey() *QueryKey {
	if x != nil {
		return x.QueryKey
	}
	return nil
}

func (x *GetSingleRunParamsRequest) GetTargetChainId() uint64 {
	if x != nil {
		return x.TargetChainId
	}
	return 0
}

type GetSingleRunParamsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Err              *ErrMsg                `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	SrcChainId       uint64                 `protobuf:"varint,2,opt,name=src_chain_id,json=srcChainId,proto3" json:"src_chain_id,omitempty"`
	ProofData        *ProofData             `protobuf:"bytes,3,opt,name=proof_data,json=proofData,proto3" json:"proof_data,omitempty"`
	MerkleRoot       string                 `protobuf:"bytes,4,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	MerkleProof      []string               `protobuf:"bytes,5,rep,name=merkle_proof,json=merkleProof,proto3" json:"merkle_proof,omitempty"`
	NodeIndex        uint64                 `protobuf:"varint,6,opt,name=node_index,json=nodeIndex,proto3" json:"node_index,omitempty"`
	AppCircuitOutput string                 `protobuf:"bytes,7,opt,name=app_circuit_output,json=appCircuitOutput,proto3" json:"app_circuit_output,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSingleRunParamsResponse) Reset() {
	*x = GetSingleRunParamsResponse{}
	mi := &file_brevis_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSingleRunParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleRunParamsResponse) ProtoMessage() {}

func (x *GetSingleRunParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleRunParamsResponse.ProtoReflect.Descriptor instead.
func (*GetSingleRunParamsResponse) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *GetSingleRunParamsResponse) GetErr() *ErrMsg {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *GetSingleRunParamsResponse) GetSrcChainId() uint64 {
	if x != nil {
		return x.SrcChainId
	}
	return 0
}

func (x *GetSingleRunParamsResponse) GetProofData() *ProofData {
	if x != nil {
		return x.ProofData
	}
	return nil
}

func (x *GetSingleRunParamsResponse) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *GetSingleRunParamsResponse) GetMerkleProof() []string {
	if x != nil {
		return x.MerkleProof
	}
	return nil
}

func (x *GetSingleRunParamsResponse) GetNodeIndex() uint64 {
	if x != nil {
		return x.NodeIndex
	}
	return 0
}

func (x *GetSingleRunParamsResponse) GetAppCircuitOutput() string {
	if x != nil {
		return x.AppCircuitOutput
	}
	return ""
}

type ProofData struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CommitHash string                 `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	// Deprecated: Marked as deprecated in brevis/gateway.proto.
	VkHash               string `protobuf:"bytes,2,opt,name=vk_hash,json=vkHash,proto3" json:"vk_hash,omitempty"`
	AppCommitHash        string `protobuf:"bytes,3,opt,name=app_commit_hash,json=appCommitHash,proto3" json:"app_commit_hash,omitempty"`
	AppVkHash            string `protobuf:"bytes,4,opt,name=app_vk_hash,json=appVkHash,proto3" json:"app_vk_hash,omitempty"`
	SmtRoot              string `protobuf:"bytes,5,opt,name=smt_root,json=smtRoot,proto3" json:"smt_root,omitempty"`
	DummyInputCommitment string `protobuf:"bytes,6,opt,name=dummy_input_commitment,json=dummyInputCommitment,proto3" json:"dummy_input_commitment,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProofData) Reset() {
	*x = ProofData{}
	mi := &file_brevis_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProofData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofData) ProtoMessage() {}

func (x *ProofData) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofData.ProtoReflect.Descriptor instead.
func (*ProofData) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *ProofData) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

// Deprecated: Marked as deprecated in brevis/gateway.proto.
func (x *ProofData) GetVkHash() string {
	if x != nil {
		return x.VkHash
	}
	return ""
}

func (x *ProofData) GetAppCommitHash() string {
	if x != nil {
		return x.AppCommitHash
	}
	return ""
}

func (x *ProofData) GetAppVkHash() string {
	if x != nil {
		return x.AppVkHash
	}
	return ""
}

func (x *ProofData) GetSmtRoot() string {
	if x != nil {
		return x.SmtRoot
	}
	return ""
}

func (x *ProofData) GetDummyInputCommitment() string {
	if x != nil {
		return x.DummyInputCommitment
	}
	return ""
}

type SendBatchQueriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Queries       []*Query               `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	TargetChainId uint64                 `protobuf:"varint,3,opt,name=target_chain_id,json=targetChainId,proto3" json:"target_chain_id,omitempty"`
	Option        QueryOption            `protobuf:"varint,4,opt,name=option,proto3,enum=brevis.QueryOption" json:"option,omitempty"`
	ApiKey        string                 `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"` // authentication
	UseVm         bool                   `protobuf:"varint,6,opt,name=use_vm,json=useVm,proto3" json:"use_vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchQueriesRequest) Reset() {
	*x = SendBatchQueriesRequest{}
	mi := &file_brevis_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchQueriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchQueriesRequest) ProtoMessage() {}

func (x *SendBatchQueriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchQueriesRequest.ProtoReflect.Descriptor instead.
func (*SendBatchQueriesRequest) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *SendBatchQueriesRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *SendBatchQueriesRequest) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *SendBatchQueriesRequest) GetTargetChainId() uint64 {
	if x != nil {
		return x.TargetChainId
	}
	return 0
}

func (x *SendBatchQueriesRequest) GetOption() QueryOption {
	if x != nil {
		return x.Option
	}
	return QueryOption_ZK_MODE
}

func (x *SendBatchQueriesRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *SendBatchQueriesRequest) GetUseVm() bool {
	if x != nil {
		return x.UseVm
	}
	return false
}

type Query struct {
	state             protoimpl.MessageState               `protogen:"open.v1"`
	ReceiptInfos      []*ReceiptInfo                       `protobuf:"bytes,1,rep,name=receipt_infos,json=receiptInfos,proto3" json:"receipt_infos,omitempty"`
	StorageQueryInfos []*StorageQueryInfo                  `protobuf:"bytes,2,rep,name=storage_query_infos,json=storageQueryInfos,proto3" json:"storage_query_infos,omitempty"`
	TransactionInfos  []*TransactionInfo                   `protobuf:"bytes,3,rep,name=transaction_infos,json=transactionInfos,proto3" json:"transaction_infos,omitempty"`
	AppCircuitInfo    *commonproto.AppCircuitInfoWithProof `protobuf:"bytes,4,opt,name=app_circuit_info,json=appCircuitInfo,proto3" json:"app_circuit_info,omitempty"`
	// Deprecated: Marked as deprecated in brevis/gateway.proto.
	UsePlonky2       bool                          `protobuf:"varint,5,opt,name=use_plonky2,json=usePlonky2,proto3" json:"use_plonky2,omitempty"`
	VmAppCircuitInfo *commonproto.VmAppCircuitInfo `protobuf:"bytes,6,opt,name=vm_app_circuit_info,json=vmAppCircuitInfo,proto3" json:"vm_app_circuit_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_brevis_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *Query) GetReceiptInfos() []*ReceiptInfo {
	if x != nil {
		return x.ReceiptInfos
	}
	return nil
}

func (x *Query) GetStorageQueryInfos() []*StorageQueryInfo {
	if x != nil {
		return x.StorageQueryInfos
	}
	return nil
}

func (x *Query) GetTransactionInfos() []*TransactionInfo {
	if x != nil {
		return x.TransactionInfos
	}
	return nil
}

func (x *Query) GetAppCircuitInfo() *commonproto.AppCircuitInfoWithProof {
	if x != nil {
		return x.AppCircuitInfo
	}
	return nil
}

// Deprecated: Marked as deprecated in brevis/gateway.proto.
func (x *Query) GetUsePlonky2() bool {
	if x != nil {
		return x.UsePlonky2
	}
	return false
}

func (x *Query) GetVmAppCircuitInfo() *commonproto.VmAppCircuitInfo {
	if x != nil {
		return x.VmAppCircuitInfo
	}
	return nil
}

type SendBatchQueriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *ErrMsg                `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	QueryKeys     []*QueryKey            `protobuf:"bytes,2,rep,name=query_keys,json=queryKeys,proto3" json:"query_keys,omitempty"`
	Fee           string                 `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchQueriesResponse) Reset() {
	*x = SendBatchQueriesResponse{}
	mi := &file_brevis_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchQueriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchQueriesResponse) ProtoMessage() {}

func (x *SendBatchQueriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchQueriesResponse.ProtoReflect.Descriptor instead.
func (*SendBatchQueriesResponse) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *SendBatchQueriesResponse) GetErr() *ErrMsg {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *SendBatchQueriesResponse) GetQueryKeys() []*QueryKey {
	if x != nil {
		return x.QueryKeys
	}
	return nil
}

func (x *SendBatchQueriesResponse) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

type QueryKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryHash     string                 `protobuf:"bytes,1,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	Nonce         uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryKey) Reset() {
	*x = QueryKey{}
	mi := &file_brevis_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKey) ProtoMessage() {}

func (x *QueryKey) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKey.ProtoReflect.Descriptor instead.
func (*QueryKey) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *QueryKey) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

func (x *QueryKey) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type SendBatchQueriesAsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *ErrMsg                `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	BatchId       string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	RequestIds    []string               `protobuf:"bytes,3,rep,name=request_ids,json=requestIds,proto3" json:"request_ids,omitempty"`
	Nonce         uint64                 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchQueriesAsyncResponse) Reset() {
	*x = SendBatchQueriesAsyncResponse{}
	mi := &file_brevis_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchQueriesAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchQueriesAsyncResponse) ProtoMessage() {}

func (x *SendBatchQueriesAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchQueriesAsyncResponse.ProtoReflect.Descriptor instead.
func (*SendBatchQueriesAsyncResponse) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *SendBatchQueriesAsyncResponse) GetErr() *ErrMsg {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *SendBatchQueriesAsyncResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *SendBatchQueriesAsyncResponse) GetRequestIds() []string {
	if x != nil {
		return x.RequestIds
	}
	return nil
}

func (x *SendBatchQueriesAsyncResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type GetQueryKeysByBatchIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryKeysByBatchIdRequest) Reset() {
	*x = GetQueryKeysByBatchIdRequest{}
	mi := &file_brevis_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryKeysByBatchIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryKeysByBatchIdRequest) ProtoMessage() {}

func (x *GetQueryKeysByBatchIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryKeysByBatchIdRequest.ProtoReflect.Descriptor instead.
func (*GetQueryKeysByBatchIdRequest) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *GetQueryKeysByBatchIdRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type GetQueryKeysByBatchIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *ErrMsg                `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	QueryKeys     []*QueryKey            `protobuf:"bytes,2,rep,name=query_keys,json=queryKeys,proto3" json:"query_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryKeysByBatchIdResponse) Reset() {
	*x = GetQueryKeysByBatchIdResponse{}
	mi := &file_brevis_gateway_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryKeysByBatchIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryKeysByBatchIdResponse) ProtoMessage() {}

func (x *GetQueryKeysByBatchIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryKeysByBatchIdResponse.ProtoReflect.Descriptor instead.
func (*GetQueryKeysByBatchIdResponse) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{18}
}

func (x *GetQueryKeysByBatchIdResponse) GetErr() *ErrMsg {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *GetQueryKeysByBatchIdResponse) GetQueryKeys() []*QueryKey {
	if x != nil {
		return x.QueryKeys
	}
	return nil
}

type CircuitDigestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircuitDigestRequest) Reset() {
	*x = CircuitDigestRequest{}
	mi := &file_brevis_gateway_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitDigestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitDigestRequest) ProtoMessage() {}

func (x *CircuitDigestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitDigestRequest.ProtoReflect.Descriptor instead.
func (*CircuitDigestRequest) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{19}
}

type CircuitDigestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *ErrMsg                `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	HashesLimbs   []uint64               `protobuf:"varint,2,rep,packed,name=hashes_limbs,json=hashesLimbs,proto3" json:"hashes_limbs,omitempty"`
	GnarkVks      []string               `protobuf:"bytes,3,rep,name=gnark_vks,json=gnarkVks,proto3" json:"gnark_vks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircuitDigestResponse) Reset() {
	*x = CircuitDigestResponse{}
	mi := &file_brevis_gateway_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitDigestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitDigestResponse) ProtoMessage() {}

func (x *CircuitDigestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitDigestResponse.ProtoReflect.Descriptor instead.
func (*CircuitDigestResponse) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{20}
}

func (x *CircuitDigestResponse) GetErr() *ErrMsg {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *CircuitDigestResponse) GetHashesLimbs() []uint64 {
	if x != nil {
		return x.HashesLimbs
	}
	return nil
}

func (x *CircuitDigestResponse) GetGnarkVks() []string {
	if x != nil {
		return x.GnarkVks
	}
	return nil
}

type CircuitDummyInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircuitDummyInputRequest) Reset() {
	*x = CircuitDummyInputRequest{}
	mi := &file_brevis_gateway_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitDummyInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitDummyInputRequest) ProtoMessage() {}

func (x *CircuitDummyInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitDummyInputRequest.ProtoReflect.Descriptor instead.
func (*CircuitDummyInputRequest) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{21}
}

func (x *CircuitDummyInputRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type CircuitDummyInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *ErrMsg                `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Receipt       string                 `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Storage       string                 `protobuf:"bytes,3,opt,name=storage,proto3" json:"storage,omitempty"`
	Tx            string                 `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircuitDummyInputResponse) Reset() {
	*x = CircuitDummyInputResponse{}
	mi := &file_brevis_gateway_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitDummyInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitDummyInputResponse) ProtoMessage() {}

func (x *CircuitDummyInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitDummyInputResponse.ProtoReflect.Descriptor instead.
func (*CircuitDummyInputResponse) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{22}
}

func (x *CircuitDummyInputResponse) GetErr() *ErrMsg {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *CircuitDummyInputResponse) GetReceipt() string {
	if x != nil {
		return x.Receipt
	}
	return ""
}

func (x *CircuitDummyInputResponse) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *CircuitDummyInputResponse) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

type SubmitVKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VkHash        string                 `protobuf:"bytes,1,opt,name=vk_hash,json=vkHash,proto3" json:"vk_hash,omitempty"`
	VkRaw         string                 `protobuf:"bytes,2,opt,name=vk_raw,json=vkRaw,proto3" json:"vk_raw,omitempty"`
	ChainId       uint64                 `protobuf:"varint,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TargetChainId uint64                 `protobuf:"varint,4,opt,name=target_chain_id,json=targetChainId,proto3" json:"target_chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitVKRequest) Reset() {
	*x = SubmitVKRequest{}
	mi := &file_brevis_gateway_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitVKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVKRequest) ProtoMessage() {}

func (x *SubmitVKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVKRequest.ProtoReflect.Descriptor instead.
func (*SubmitVKRequest) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{23}
}

func (x *SubmitVKRequest) GetVkHash() string {
	if x != nil {
		return x.VkHash
	}
	return ""
}

func (x *SubmitVKRequest) GetVkRaw() string {
	if x != nil {
		return x.VkRaw
	}
	return ""
}

func (x *SubmitVKRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *SubmitVKRequest) GetTargetChainId() uint64 {
	if x != nil {
		return x.TargetChainId
	}
	return 0
}

type SubmitVKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *ErrMsg                `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitVKResponse) Reset() {
	*x = SubmitVKResponse{}
	mi := &file_brevis_gateway_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitVKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVKResponse) ProtoMessage() {}

func (x *SubmitVKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_gateway_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVKResponse.ProtoReflect.Descriptor instead.
func (*SubmitVKResponse) Descriptor() ([]byte, []int) {
	return file_brevis_gateway_proto_rawDescGZIP(), []int{24}
}

func (x *SubmitVKResponse) GetErr() *ErrMsg {
	if x != nil {
		return x.Err
	}
	return nil
}

var File_brevis_gateway_proto protoreflect.FileDescriptor

const file_brevis_gateway_proto_rawDesc = "" +
	"\n" +
	"\x14brevis/gateway.proto\x12\x06brevis\x1a\x12brevis/types.proto\x1a\x19common/circuit_data.proto\x1a\x1cgoogle/api/annotations.proto\"?\n" +
	"\x06ErrMsg\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.brevis.ErrCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x96\x04\n" +
	"\x13PrepareQueryRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x128\n" +
	"\rreceipt_infos\x18\x02 \x03(\v2\x13.brevis.ReceiptInfoR\freceiptInfos\x12H\n" +
	"\x13storage_query_infos\x18\x03 \x03(\v2\x18.brevis.StorageQueryInfoR\x11storageQueryInfos\x12D\n" +
	"\x11transaction_infos\x18\x04 \x03(\v2\x17.brevis.TransactionInfoR\x10transactionInfos\x12@\n" +
	"\x10app_circuit_info\x18\x05 \x01(\v2\x16.common.AppCircuitInfoR\x0eappCircuitInfo\x12&\n" +
	"\x0ftarget_chain_id\x18\x06 \x01(\x04R\rtargetChainId\x12+\n" +
	"\x06option\x18\a \x01(\x0e2\x13.brevis.QueryOptionR\x06option\x12#\n" +
	"\vuse_plonky2\x18\b \x01(\bB\x02\x18\x01R\n" +
	"usePlonky2\x12\x15\n" +
	"\x06use_vm\x18\t \x01(\bR\x05useVm\x12G\n" +
	"\x13vm_app_circuit_info\x18\n" +
	" \x01(\v2\x18.common.VmAppCircuitInfoR\x10vmAppCircuitInfo\"y\n" +
	"\x14PrepareQueryResponse\x12 \n" +
	"\x03err\x18\x01 \x01(\v2\x0e.brevis.ErrMsgR\x03err\x12-\n" +
	"\tquery_key\x18\x02 \x01(\v2\x10.brevis.QueryKeyR\bqueryKey\x12\x10\n" +
	"\x03fee\x18\x03 \x01(\tR\x03fee\"\x9f\x02\n" +
	"\x1cSubmitAppCircuitProofRequest\x12-\n" +
	"\tquery_key\x18\x01 \x01(\v2\x10.brevis.QueryKeyR\bqueryKey\x12&\n" +
	"\x0ftarget_chain_id\x18\x02 \x01(\x04R\rtargetChainId\x12\x14\n" +
	"\x05proof\x18\x03 \x01(\tR\x05proof\x12I\n" +
	"\x10app_circuit_info\x18\x04 \x01(\v2\x1f.common.AppCircuitInfoWithProofR\x0eappCircuitInfo\x12G\n" +
	"\x13vm_app_circuit_info\x18\x05 \x01(\v2\x18.common.VmAppCircuitInfoR\x10vmAppCircuitInfo\"[\n" +
	"\x1dSubmitAppCircuitProofResponse\x12 \n" +
	"\x03err\x18\x01 \x01(\v2\x0e.brevis.ErrMsgR\x03err\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"n\n" +
	"\x15GetQueryStatusRequest\x12-\n" +
	"\tquery_key\x18\x01 \x01(\v2\x10.brevis.QueryKeyR\bqueryKey\x12&\n" +
	"\x0ftarget_chain_id\x18\x02 \x01(\x04R\rtargetChainId\"\xa8\x02\n" +
	"\x16GetQueryStatusResponse\x12 \n" +
	"\x03err\x18\x01 \x01(\v2\x0e.brevis.ErrMsgR\x03err\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.brevis.QueryStatusR\x06status\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12\x14\n" +
	"\x05proof\x18\x04 \x01(\tR\x05proof\x120\n" +
	"\n" +
	"proof_data\x18\x05 \x01(\v2\x11.brevis.ProofDataR\tproofData\x12%\n" +
	"\x0ecircuit_output\x18\x06 \x01(\tR\rcircuitOutput\x127\n" +
	"\x18proof_with_public_inputs\x18\a \x01(\tR\x15proofWithPublicInputs\"a\n" +
	"\x18GetQueryInfoForOPRequest\x12\x1d\n" +
	"\n" +
	"query_hash\x18\x01 \x01(\tR\tqueryHash\x12&\n" +
	"\x0ftarget_chain_id\x18\x02 \x01(\x04R\rtargetChainId\"\\\n" +
	"\x19GetQueryInfoForOPResponse\x12 \n" +
	"\x03err\x18\x01 \x01(\v2\x0e.brevis.ErrMsgR\x03err\x12\x1d\n" +
	"\n" +
	"query_info\x18\x02 \x01(\fR\tqueryInfo\"r\n" +
	"\x19GetSingleRunParamsRequest\x12-\n" +
	"\tquery_key\x18\x01 \x01(\v2\x10.brevis.QueryKeyR\bqueryKey\x12&\n" +
	"\x0ftarget_chain_id\x18\x02 \x01(\x04R\rtargetChainId\"\xa3\x02\n" +
	"\x1aGetSingleRunParamsResponse\x12 \n" +
	"\x03err\x18\x01 \x01(\v2\x0e.brevis.ErrMsgR\x03err\x12 \n" +
	"\fsrc_chain_id\x18\x02 \x01(\x04R\n" +
	"srcChainId\x120\n" +
	"\n" +
	"proof_data\x18\x03 \x01(\v2\x11.brevis.ProofDataR\tproofData\x12\x1f\n" +
	"\vmerkle_root\x18\x04 \x01(\tR\n" +
	"merkleRoot\x12!\n" +
	"\fmerkle_proof\x18\x05 \x03(\tR\vmerkleProof\x12\x1d\n" +
	"\n" +
	"node_index\x18\x06 \x01(\x04R\tnodeIndex\x12,\n" +
	"\x12app_circuit_output\x18\a \x01(\tR\x10appCircuitOutput\"\xe2\x01\n" +
	"\tProofData\x12\x1f\n" +
	"\vcommit_hash\x18\x01 \x01(\tR\n" +
	"commitHash\x12\x1b\n" +
	"\avk_hash\x18\x02 \x01(\tB\x02\x18\x01R\x06vkHash\x12&\n" +
	"\x0fapp_commit_hash\x18\x03 \x01(\tR\rappCommitHash\x12\x1e\n" +
	"\vapp_vk_hash\x18\x04 \x01(\tR\tappVkHash\x12\x19\n" +
	"\bsmt_root\x18\x05 \x01(\tR\asmtRoot\x124\n" +
	"\x16dummy_input_commitment\x18\x06 \x01(\tR\x14dummyInputCommitment\"\xe2\x01\n" +
	"\x17SendBatchQueriesRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12'\n" +
	"\aqueries\x18\x02 \x03(\v2\r.brevis.QueryR\aqueries\x12&\n" +
	"\x0ftarget_chain_id\x18\x03 \x01(\x04R\rtargetChainId\x12+\n" +
	"\x06option\x18\x04 \x01(\x0e2\x13.brevis.QueryOptionR\x06option\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\x12\x15\n" +
	"\x06use_vm\x18\x06 \x01(\bR\x05useVm\"\x8a\x03\n" +
	"\x05Query\x128\n" +
	"\rreceipt_infos\x18\x01 \x03(\v2\x13.brevis.ReceiptInfoR\freceiptInfos\x12H\n" +
	"\x13storage_query_infos\x18\x02 \x03(\v2\x18.brevis.StorageQueryInfoR\x11storageQueryInfos\x12D\n" +
	"\x11transaction_infos\x18\x03 \x03(\v2\x17.brevis.TransactionInfoR\x10transactionInfos\x12I\n" +
	"\x10app_circuit_info\x18\x04 \x01(\v2\x1f.common.AppCircuitInfoWithProofR\x0eappCircuitInfo\x12#\n" +
	"\vuse_plonky2\x18\x05 \x01(\bB\x02\x18\x01R\n" +
	"usePlonky2\x12G\n" +
	"\x13vm_app_circuit_info\x18\x06 \x01(\v2\x18.common.VmAppCircuitInfoR\x10vmAppCircuitInfo\"\x7f\n" +
	"\x18SendBatchQueriesResponse\x12 \n" +
	"\x03err\x18\x01 \x01(\v2\x0e.brevis.ErrMsgR\x03err\x12/\n" +
	"\n" +
	"query_keys\x18\x02 \x03(\v2\x10.brevis.QueryKeyR\tqueryKeys\x12\x10\n" +
	"\x03fee\x18\x03 \x01(\tR\x03fee\"?\n" +
	"\bQueryKey\x12\x1d\n" +
	"\n" +
	"query_hash\x18\x01 \x01(\tR\tqueryHash\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\"\x93\x01\n" +
	"\x1dSendBatchQueriesAsyncResponse\x12 \n" +
	"\x03err\x18\x01 \x01(\v2\x0e.brevis.ErrMsgR\x03err\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\x12\x1f\n" +
	"\vrequest_ids\x18\x03 \x03(\tR\n" +
	"requestIds\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonce\"9\n" +
	"\x1cGetQueryKeysByBatchIdRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\"r\n" +
	"\x1dGetQueryKeysByBatchIdResponse\x12 \n" +
	"\x03err\x18\x01 \x01(\v2\x0e.brevis.ErrMsgR\x03err\x12/\n" +
	"\n" +
	"query_keys\x18\x02 \x03(\v2\x10.brevis.QueryKeyR\tqueryKeys\"\x16\n" +
	"\x14CircuitDigestRequest\"y\n" +
	"\x15CircuitDigestResponse\x12 \n" +
	"\x03err\x18\x01 \x01(\v2\x0e.brevis.ErrMsgR\x03err\x12!\n" +
	"\fhashes_limbs\x18\x02 \x03(\x04R\vhashesLimbs\x12\x1b\n" +
	"\tgnark_vks\x18\x03 \x03(\tR\bgnarkVks\"5\n" +
	"\x18CircuitDummyInputRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\"\x81\x01\n" +
	"\x19CircuitDummyInputResponse\x12 \n" +
	"\x03err\x18\x01 \x01(\v2\x0e.brevis.ErrMsgR\x03err\x12\x18\n" +
	"\areceipt\x18\x02 \x01(\tR\areceipt\x12\x18\n" +
	"\astorage\x18\x03 \x01(\tR\astorage\x12\x0e\n" +
	"\x02tx\x18\x04 \x01(\tR\x02tx\"\x84\x01\n" +
	"\x0fSubmitVKRequest\x12\x17\n" +
	"\avk_hash\x18\x01 \x01(\tR\x06vkHash\x12\x15\n" +
	"\x06vk_raw\x18\x02 \x01(\tR\x05vkRaw\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\x04R\achainId\x12&\n" +
	"\x0ftarget_chain_id\x18\x04 \x01(\x04R\rtargetChainId\"4\n" +
	"\x10SubmitVKResponse\x12 \n" +
	"\x03err\x18\x01 \x01(\v2\x0e.brevis.ErrMsgR\x03err*\x8a\x01\n" +
	"\aErrCode\x12\x18\n" +
	"\x14ERROR_CODE_UNDEFINED\x10\x00\x121\n" +
	"-ERROR_CODE_SLOT_VALUE_PROOF_GENERATION_FAILED\x10\x01\x122\n" +
	".ERROR_CODE_TRANSACTION_PROOF_GENERATION_FAILED\x10\x02*,\n" +
	"\vCheckStatus\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x00\x12\f\n" +
	"\bCOMPLETE\x10\x01*'\n" +
	"\vQueryOption\x12\v\n" +
	"\aZK_MODE\x10\x00\x12\v\n" +
	"\aOP_MODE\x10\x01*\xac\x03\n" +
	"\vQueryStatus\x12\x0e\n" +
	"\n" +
	"QS_UNKNOWN\x10\x00\x12\x11\n" +
	"\rQS_TO_BE_PAID\x10\x01\x12\v\n" +
	"\aQS_PAID\x10\x02\x12\x12\n" +
	"\x0eQS_PROOF_READY\x10\x03\x12\x0f\n" +
	"\vQS_COMPLETE\x10\x04\x12\r\n" +
	"\tQS_FAILED\x10\x05\x12\x19\n" +
	"\x15QS_OP_MESSAGE_PENDING\x10\x06\x12\x17\n" +
	"\x13QS_OP_MESSAGE_READY\x10\a\x12\x13\n" +
	"\x0fQS_OP_SUBMITTED\x10\b\x12#\n" +
	"\x1fQS_OP_MESSAGE_SUBMISSION_FAILED\x10\t\x12\x13\n" +
	"\x0fQS_OP_DISPUTING\x10\n" +
	"\x12\x1c\n" +
	"\x18QS_OP_ASK_FOR_QUERY_DATA\x10\v\x12\x1e\n" +
	"\x1aQS_OP_QUERY_DATA_SUBMITTED\x10\f\x12 \n" +
	"\x1cQS_OP_QUERY_DATA_POST_FAILED\x10\r\x12\x1d\n" +
	"\x19QS_OP_ASK_FOR_QUERY_PROOF\x10\x0e\x12\x12\n" +
	"\x0eQS_OP_DISPUTED\x10\x0f\x12\x12\n" +
	"\x0eQS_OP_ATTESTED\x10\x10\x12\x0f\n" +
	"\vQS_REFUNDED\x10\x112\xb9\n" +
	"\n" +
	"\aGateway\x12f\n" +
	"\fPrepareQuery\x12\x1b.brevis.PrepareQueryRequest\x1a\x1c.brevis.PrepareQueryResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/zk/prepareQuery\x12\x8a\x01\n" +
	"\x15SubmitAppCircuitProof\x12$.brevis.SubmitAppCircuitProofRequest\x1a%.brevis.SubmitAppCircuitProofResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/zk/submitAppCircuitProof\x12k\n" +
	"\x0eGetQueryStatus\x12\x1d.brevis.GetQueryStatusRequest\x1a\x1e.brevis.GetQueryStatusResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/zk/getQueryStatus\x12w\n" +
	"\x11GetQueryInfoForOP\x12 .brevis.GetQueryInfoForOPRequest\x1a!.brevis.GetQueryInfoForOPResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/zk/getQueryInfoForOP\x12{\n" +
	"\x12GetSingleRunParams\x12!.brevis.GetSingleRunParamsRequest\x1a\".brevis.GetSingleRunParamsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/zk/getSingleRunParams\x12v\n" +
	"\x10SendBatchQueries\x12\x1f.brevis.SendBatchQueriesRequest\x1a .brevis.SendBatchQueriesResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/zk/sendBatchQueries\x12\x85\x01\n" +
	"\x15SendBatchQueriesAsync\x12\x1f.brevis.SendBatchQueriesRequest\x1a%.brevis.SendBatchQueriesAsyncResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/zk/sendBatchQueriesAsync\x12\x87\x01\n" +
	"\x15GetQueryKeysByBatchId\x12$.brevis.GetQueryKeysByBatchIdRequest\x1a%.brevis.GetQueryKeysByBatchIdResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/zk/getQueryKeysByBatchId\x12m\n" +
	"\x10GetCircuitDigest\x12\x1c.brevis.CircuitDigestRequest\x1a\x1d.brevis.CircuitDigestResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/zk/getCircuitDigest\x12\x84\x01\n" +
	"\x1bGetCircuitDummyInputRequest\x12 .brevis.CircuitDummyInputRequest\x1a!.brevis.CircuitDummyInputResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/zk/getCircuitDummyInput\x12V\n" +
	"\bSubmitVK\x12\x17.brevis.SubmitVKRequest\x1a\x18.brevis.SubmitVKResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/zk/submitVKb\x06proto3"

var (
	file_brevis_gateway_proto_rawDescOnce sync.Once
	file_brevis_gateway_proto_rawDescData []byte
)

func file_brevis_gateway_proto_rawDescGZIP() []byte {
	file_brevis_gateway_proto_rawDescOnce.Do(func() {
		file_brevis_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brevis_gateway_proto_rawDesc), len(file_brevis_gateway_proto_rawDesc)))
	})
	return file_brevis_gateway_proto_rawDescData
}

var file_brevis_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_brevis_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_brevis_gateway_proto_goTypes = []any{
	(ErrCode)(0),                                // 0: brevis.ErrCode
	(CheckStatus)(0),                            // 1: brevis.CheckStatus
	(QueryOption)(0),                            // 2: brevis.QueryOption
	(QueryStatus)(0),                            // 3: brevis.QueryStatus
	(*ErrMsg)(nil),                              // 4: brevis.ErrMsg
	(*PrepareQueryRequest)(nil),                 // 5: brevis.PrepareQueryRequest
	(*PrepareQueryResponse)(nil),                // 6: brevis.PrepareQueryResponse
	(*SubmitAppCircuitProofRequest)(nil),        // 7: brevis.SubmitAppCircuitProofRequest
	(*SubmitAppCircuitProofResponse)(nil),       // 8: brevis.SubmitAppCircuitProofResponse
	(*GetQueryStatusRequest)(nil),               // 9: brevis.GetQueryStatusRequest
	(*GetQueryStatusResponse)(nil),              // 10: brevis.GetQueryStatusResponse
	(*GetQueryInfoForOPRequest)(nil),            // 11: brevis.GetQueryInfoForOPRequest
	(*GetQueryInfoForOPResponse)(nil),           // 12: brevis.GetQueryInfoForOPResponse
	(*GetSingleRunParamsRequest)(nil),           // 13: brevis.GetSingleRunParamsRequest
	(*GetSingleRunParamsResponse)(nil),          // 14: brevis.GetSingleRunParamsResponse
	(*ProofData)(nil),                           // 15: brevis.ProofData
	(*SendBatchQueriesRequest)(nil),             // 16: brevis.SendBatchQueriesRequest
	(*Query)(nil),                               // 17: brevis.Query
	(*SendBatchQueriesResponse)(nil),            // 18: brevis.SendBatchQueriesResponse
	(*QueryKey)(nil),                            // 19: brevis.QueryKey
	(*SendBatchQueriesAsyncResponse)(nil),       // 20: brevis.SendBatchQueriesAsyncResponse
	(*GetQueryKeysByBatchIdRequest)(nil),        // 21: brevis.GetQueryKeysByBatchIdRequest
	(*GetQueryKeysByBatchIdResponse)(nil),       // 22: brevis.GetQueryKeysByBatchIdResponse
	(*CircuitDigestRequest)(nil),                // 23: brevis.CircuitDigestRequest
	(*CircuitDigestResponse)(nil),               // 24: brevis.CircuitDigestResponse
	(*CircuitDummyInputRequest)(nil),            // 25: brevis.CircuitDummyInputRequest
	(*CircuitDummyInputResponse)(nil),           // 26: brevis.CircuitDummyInputResponse
	(*SubmitVKRequest)(nil),                     // 27: brevis.SubmitVKRequest
	(*SubmitVKResponse)(nil),                    // 28: brevis.SubmitVKResponse
	(*ReceiptInfo)(nil),                         // 29: brevis.ReceiptInfo
	(*StorageQueryInfo)(nil),                    // 30: brevis.StorageQueryInfo
	(*TransactionInfo)(nil),                     // 31: brevis.TransactionInfo
	(*commonproto.AppCircuitInfo)(nil),          // 32: common.AppCircuitInfo
	(*commonproto.VmAppCircuitInfo)(nil),        // 33: common.VmAppCircuitInfo
	(*commonproto.AppCircuitInfoWithProof)(nil), // 34: common.AppCircuitInfoWithProof
}
var file_brevis_gateway_proto_depIdxs = []int32{
	0,  // 0: brevis.ErrMsg.code:type_name -> brevis.ErrCode
	29, // 1: brevis.PrepareQueryRequest.receipt_infos:type_name -> brevis.ReceiptInfo
	30, // 2: brevis.PrepareQueryRequest.storage_query_infos:type_name -> brevis.StorageQueryInfo
	31, // 3: brevis.PrepareQueryRequest.transaction_infos:type_name -> brevis.TransactionInfo
	32, // 4: brevis.PrepareQueryRequest.app_circuit_info:type_name -> common.AppCircuitInfo
	2,  // 5: brevis.PrepareQueryRequest.option:type_name -> brevis.QueryOption
	33, // 6: brevis.PrepareQueryRequest.vm_app_circuit_info:type_name -> common.VmAppCircuitInfo
	4,  // 7: brevis.PrepareQueryResponse.err:type_name -> brevis.ErrMsg
	19, // 8: brevis.PrepareQueryResponse.query_key:type_name -> brevis.QueryKey
	19, // 9: brevis.SubmitAppCircuitProofRequest.query_key:type_name -> brevis.QueryKey
	34, // 10: brevis.SubmitAppCircuitProofRequest.app_circuit_info:type_name -> common.AppCircuitInfoWithProof
	33, // 11: brevis.SubmitAppCircuitProofRequest.vm_app_circuit_info:type_name -> common.VmAppCircuitInfo
	4,  // 12: brevis.SubmitAppCircuitProofResponse.err:type_name -> brevis.ErrMsg
	19, // 13: brevis.GetQueryStatusRequest.query_key:type_name -> brevis.QueryKey
	4,  // 14: brevis.GetQueryStatusResponse.err:type_name -> brevis.ErrMsg
	3,  // 15: brevis.GetQueryStatusResponse.status:type_name -> brevis.QueryStatus
	15, // 16: brevis.GetQueryStatusResponse.proof_data:type_name -> brevis.ProofData
	4,  // 17: brevis.GetQueryInfoForOPResponse.err:type_name -> brevis.ErrMsg
	19, // 18: brevis.GetSingleRunParamsRequest.query_key:type_name -> brevis.QueryKey
	4,  // 19: brevis.GetSingleRunParamsResponse.err:type_name -> brevis.ErrMsg
	15, // 20: brevis.GetSingleRunParamsResponse.proof_data:type_name -> brevis.ProofData
	17, // 21: brevis.SendBatchQueriesRequest.queries:type_name -> brevis.Query
	2,  // 22: brevis.SendBatchQueriesRequest.option:type_name -> brevis.QueryOption
	29, // 23: brevis.Query.receipt_infos:type_name -> brevis.ReceiptInfo
	30, // 24: brevis.Query.storage_query_infos:type_name -> brevis.StorageQueryInfo
	31, // 25: brevis.Query.transaction_infos:type_name -> brevis.TransactionInfo
	34, // 26: brevis.Query.app_circuit_info:type_name -> common.AppCircuitInfoWithProof
	33, // 27: brevis.Query.vm_app_circuit_info:type_name -> common.VmAppCircuitInfo
	4,  // 28: brevis.SendBatchQueriesResponse.err:type_name -> brevis.ErrMsg
	19, // 29: brevis.SendBatchQueriesResponse.query_keys:type_name -> brevis.QueryKey
	4,  // 30: brevis.SendBatchQueriesAsyncResponse.err:type_name -> brevis.ErrMsg
	4,  // 31: brevis.GetQueryKeysByBatchIdResponse.err:type_name -> brevis.ErrMsg
	19, // 32: brevis.GetQueryKeysByBatchIdResponse.query_keys:type_name -> brevis.QueryKey
	4,  // 33: brevis.CircuitDigestResponse.err:type_name -> brevis.ErrMsg
	4,  // 34: brevis.CircuitDummyInputResponse.err:type_name -> brevis.ErrMsg
	4,  // 35: brevis.SubmitVKResponse.err:type_name -> brevis.ErrMsg
	5,  // 36: brevis.Gateway.PrepareQuery:input_type -> brevis.PrepareQueryRequest
	7,  // 37: brevis.Gateway.SubmitAppCircuitProof:input_type -> brevis.SubmitAppCircuitProofRequest
	9,  // 38: brevis.Gateway.GetQueryStatus:input_type -> brevis.GetQueryStatusRequest
	11, // 39: brevis.Gateway.GetQueryInfoForOP:input_type -> brevis.GetQueryInfoForOPRequest
	13, // 40: brevis.Gateway.GetSingleRunParams:input_type -> brevis.GetSingleRunParamsRequest
	16, // 41: brevis.Gateway.SendBatchQueries:input_type -> brevis.SendBatchQueriesRequest
	16, // 42: brevis.Gateway.SendBatchQueriesAsync:input_type -> brevis.SendBatchQueriesRequest
	21, // 43: brevis.Gateway.GetQueryKeysByBatchId:input_type -> brevis.GetQueryKeysByBatchIdRequest
	23, // 44: brevis.Gateway.GetCircuitDigest:input_type -> brevis.CircuitDigestRequest
	25, // 45: brevis.Gateway.GetCircuitDummyInputRequest:input_type -> brevis.CircuitDummyInputRequest
	27, // 46: brevis.Gateway.SubmitVK:input_type -> brevis.SubmitVKRequest
	6,  // 47: brevis.Gateway.PrepareQuery:output_type -> brevis.PrepareQueryResponse
	8,  // 48: brevis.Gateway.SubmitAppCircuitProof:output_type -> brevis.SubmitAppCircuitProofResponse
	10, // 49: brevis.Gateway.GetQueryStatus:output_type -> brevis.GetQueryStatusResponse
	12, // 50: brevis.Gateway.GetQueryInfoForOP:output_type -> brevis.GetQueryInfoForOPResponse
	14, // 51: brevis.Gateway.GetSingleRunParams:output_type -> brevis.GetSingleRunParamsResponse
	18, // 52: brevis.Gateway.SendBatchQueries:output_type -> brevis.SendBatchQueriesResponse
	20, // 53: brevis.Gateway.SendBatchQueriesAsync:output_type -> brevis.SendBatchQueriesAsyncResponse
	22, // 54: brevis.Gateway.GetQueryKeysByBatchId:output_type -> brevis.GetQueryKeysByBatchIdResponse
	24, // 55: brevis.Gateway.GetCircuitDigest:output_type -> brevis.CircuitDigestResponse
	26, // 56: brevis.Gateway.GetCircuitDummyInputRequest:output_type -> brevis.CircuitDummyInputResponse
	28, // 57: brevis.Gateway.SubmitVK:output_type -> brevis.SubmitVKResponse
	47, // [47:58] is the sub-list for method output_type
	36, // [36:47] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_brevis_gateway_proto_init() }
func file_brevis_gateway_proto_init() {
	if File_brevis_gateway_proto != nil {
		return
	}
	file_brevis_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brevis_gateway_proto_rawDesc), len(file_brevis_gateway_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brevis_gateway_proto_goTypes,
		DependencyIndexes: file_brevis_gateway_proto_depIdxs,
		EnumInfos:         file_brevis_gateway_proto_enumTypes,
		MessageInfos:      file_brevis_gateway_proto_msgTypes,
	}.Build()
	File_brevis_gateway_proto = out.File
	file_brevis_gateway_proto_goTypes = nil
	file_brevis_gateway_proto_depIdxs = nil
}
