// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: brevis/types.proto

package gwproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceiptInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionHash string                 `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	LogExtractInfos []*LogExtractInfo      `protobuf:"bytes,2,rep,name=log_extract_infos,json=logExtractInfos,proto3" json:"log_extract_infos,omitempty"`
	BlkNum          uint64                 `protobuf:"varint,3,opt,name=blk_num,json=blkNum,proto3" json:"blk_num,omitempty"`
	ReceiptIndex    uint64                 `protobuf:"varint,4,opt,name=receipt_index,json=receiptIndex,proto3" json:"receipt_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReceiptInfo) Reset() {
	*x = ReceiptInfo{}
	mi := &file_brevis_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptInfo) ProtoMessage() {}

func (x *ReceiptInfo) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptInfo.ProtoReflect.Descriptor instead.
func (*ReceiptInfo) Descriptor() ([]byte, []int) {
	return file_brevis_types_proto_rawDescGZIP(), []int{0}
}

func (x *ReceiptInfo) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *ReceiptInfo) GetLogExtractInfos() []*LogExtractInfo {
	if x != nil {
		return x.LogExtractInfos
	}
	return nil
}

func (x *ReceiptInfo) GetBlkNum() uint64 {
	if x != nil {
		return x.BlkNum
	}
	return 0
}

func (x *ReceiptInfo) GetReceiptIndex() uint64 {
	if x != nil {
		return x.ReceiptIndex
	}
	return 0
}

type LogExtractInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	LogPos          uint64                 `protobuf:"varint,2,opt,name=log_pos,json=logPos,proto3" json:"log_pos,omitempty"`
	LogTopic0       string                 `protobuf:"bytes,3,opt,name=log_topic0,json=logTopic0,proto3" json:"log_topic0,omitempty"`
	ValueFromTopic  bool                   `protobuf:"varint,4,opt,name=value_from_topic,json=valueFromTopic,proto3" json:"value_from_topic,omitempty"`
	ValueIndex      uint64                 `protobuf:"varint,5,opt,name=value_index,json=valueIndex,proto3" json:"value_index,omitempty"`
	Value           string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	TopicsLength    uint64                 `protobuf:"varint,7,opt,name=topics_length,json=topicsLength,proto3" json:"topics_length,omitempty"` // How many topics exists in this log
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogExtractInfo) Reset() {
	*x = LogExtractInfo{}
	mi := &file_brevis_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogExtractInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogExtractInfo) ProtoMessage() {}

func (x *LogExtractInfo) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogExtractInfo.ProtoReflect.Descriptor instead.
func (*LogExtractInfo) Descriptor() ([]byte, []int) {
	return file_brevis_types_proto_rawDescGZIP(), []int{1}
}

func (x *LogExtractInfo) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *LogExtractInfo) GetLogPos() uint64 {
	if x != nil {
		return x.LogPos
	}
	return 0
}

func (x *LogExtractInfo) GetLogTopic0() string {
	if x != nil {
		return x.LogTopic0
	}
	return ""
}

func (x *LogExtractInfo) GetValueFromTopic() bool {
	if x != nil {
		return x.ValueFromTopic
	}
	return false
}

func (x *LogExtractInfo) GetValueIndex() uint64 {
	if x != nil {
		return x.ValueIndex
	}
	return 0
}

func (x *LogExtractInfo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LogExtractInfo) GetTopicsLength() uint64 {
	if x != nil {
		return x.TopicsLength
	}
	return 0
}

type StorageQueryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	StorageKeys   []string               `protobuf:"bytes,2,rep,name=storage_keys,json=storageKeys,proto3" json:"storage_keys,omitempty"`
	BlkNum        uint64                 `protobuf:"varint,3,opt,name=blk_num,json=blkNum,proto3" json:"blk_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageQueryInfo) Reset() {
	*x = StorageQueryInfo{}
	mi := &file_brevis_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageQueryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageQueryInfo) ProtoMessage() {}

func (x *StorageQueryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageQueryInfo.ProtoReflect.Descriptor instead.
func (*StorageQueryInfo) Descriptor() ([]byte, []int) {
	return file_brevis_types_proto_rawDescGZIP(), []int{2}
}

func (x *StorageQueryInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *StorageQueryInfo) GetStorageKeys() []string {
	if x != nil {
		return x.StorageKeys
	}
	return nil
}

func (x *StorageQueryInfo) GetBlkNum() uint64 {
	if x != nil {
		return x.BlkNum
	}
	return 0
}

type TransactionInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionHash string                 `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	mi := &file_brevis_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_brevis_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_brevis_types_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionInfo) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

var File_brevis_types_proto protoreflect.FileDescriptor

const file_brevis_types_proto_rawDesc = "" +
	"\n" +
	"\x12brevis/types.proto\x12\x06brevis\"\xba\x01\n" +
	"\vReceiptInfo\x12)\n" +
	"\x10transaction_hash\x18\x01 \x01(\tR\x0ftransactionHash\x12B\n" +
	"\x11log_extract_infos\x18\x02 \x03(\v2\x16.brevis.LogExtractInfoR\x0flogExtractInfos\x12\x17\n" +
	"\ablk_num\x18\x03 \x01(\x04R\x06blkNum\x12#\n" +
	"\rreceipt_index\x18\x04 \x01(\x04R\freceiptIndex\"\xf9\x01\n" +
	"\x0eLogExtractInfo\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x17\n" +
	"\alog_pos\x18\x02 \x01(\x04R\x06logPos\x12\x1d\n" +
	"\n" +
	"log_topic0\x18\x03 \x01(\tR\tlogTopic0\x12(\n" +
	"\x10value_from_topic\x18\x04 \x01(\bR\x0evalueFromTopic\x12\x1f\n" +
	"\vvalue_index\x18\x05 \x01(\x04R\n" +
	"valueIndex\x12\x14\n" +
	"\x05value\x18\x06 \x01(\tR\x05value\x12#\n" +
	"\rtopics_length\x18\a \x01(\x04R\ftopicsLength\"h\n" +
	"\x10StorageQueryInfo\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12!\n" +
	"\fstorage_keys\x18\x02 \x03(\tR\vstorageKeys\x12\x17\n" +
	"\ablk_num\x18\x03 \x01(\x04R\x06blkNum\"<\n" +
	"\x0fTransactionInfo\x12)\n" +
	"\x10transaction_hash\x18\x01 \x01(\tR\x0ftransactionHashb\x06proto3"

var (
	file_brevis_types_proto_rawDescOnce sync.Once
	file_brevis_types_proto_rawDescData []byte
)

func file_brevis_types_proto_rawDescGZIP() []byte {
	file_brevis_types_proto_rawDescOnce.Do(func() {
		file_brevis_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brevis_types_proto_rawDesc), len(file_brevis_types_proto_rawDesc)))
	})
	return file_brevis_types_proto_rawDescData
}

var file_brevis_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_brevis_types_proto_goTypes = []any{
	(*ReceiptInfo)(nil),      // 0: brevis.ReceiptInfo
	(*LogExtractInfo)(nil),   // 1: brevis.LogExtractInfo
	(*StorageQueryInfo)(nil), // 2: brevis.StorageQueryInfo
	(*TransactionInfo)(nil),  // 3: brevis.TransactionInfo
}
var file_brevis_types_proto_depIdxs = []int32{
	1, // 0: brevis.ReceiptInfo.log_extract_infos:type_name -> brevis.LogExtractInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_brevis_types_proto_init() }
func file_brevis_types_proto_init() {
	if File_brevis_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brevis_types_proto_rawDesc), len(file_brevis_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brevis_types_proto_goTypes,
		DependencyIndexes: file_brevis_types_proto_depIdxs,
		MessageInfos:      file_brevis_types_proto_msgTypes,
	}.Build()
	File_brevis_types_proto = out.File
	file_brevis_types_proto_goTypes = nil
	file_brevis_types_proto_depIdxs = nil
}
